ci: add docker build check

diff --git a/.github/workflows/mono-ci.yml b/.github/workflows/mono-ci.yml
--- a/.github/workflows/mono-ci.yml
+++ b/.github/workflows/mono-ci.yml
@@ -9,8 +9,7 @@ jobs:
     outputs:
       changed_dirs: ${{ steps.changed-dirs.outputs.changed_dirs }}
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v4
         with:
           fetch-depth: 0
       - name: Get changed directories
@@ -30,15 +29,31 @@ jobs:
             | sort | uniq -d | jq -Rsc 'split("\n")[0:-1]')
           echo "changed_dirs=$CHANGED_DIRS" >> "$GITHUB_OUTPUT"
           cat "$GITHUB_OUTPUT"
-  process-changes:
+  docker-build:
     needs: detect-changes
     runs-on: ubuntu-latest
     strategy:
       matrix:
         changed_dir: ${{ fromJson(needs.detect-changes.outputs.changed_dirs) }}
+    defaults:
+      run:
+        working-directory: ${{ matrix.changed_dir }}
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-      - name: Execute process
+      - uses: actions/checkout@v4
+      - uses: docker/setup-qemu-action@v3
+      - uses: docker/setup-buildx-action@v3
+      - name: Build Docker images
         run: |
-          echo "Changed directory: ${{ matrix.changed_dir }}"
+          PARALLEL_JOBS=10
+
+          find . -maxdepth 1 -name "Dockerfile.*" -print0 | parallel -0 -j "$PARALLEL_JOBS" sh '
+              dockerfile="{}"
+              dirname=$(dirname "$dockerfile")
+              build_context="$dirname"
+
+              echo "Building image: from $dockerfile"
+              docker buildx build -f "$dockerfile" "$build_context"
+              if [ $? -ne 0 ]; then
+                  echo "Error building image: from $dockerfile" >&2
+              fi
+          '
